/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package swinga.view;

import java.awt.BorderLayout;
import java.awt.Component;
import javax.swing.JPanel;

/**
 *
 * @author Administrateur
 */
public class JPanelPrincipale extends javax.swing.JPanel {

    
   public void remplaceComposanCentral (JPanel NouveauPanneau){
       
       //supprime le panneau du centre s'il existe 
       BorderLayout layout = (BorderLayout)this.getLayout();
       Component component = layout.getLayoutComponent(BorderLayout.CENTER);
       if (component!=null){
           this.remove(component);
       }
       
       //Ajouter un NouveauPanneau au centre 
       this.add(NouveauPanneau  ,BorderLayout.CENTER);
       
       //Raffraichit l'affichage de l'objet actuel(un JPanelPrincipal donc) et 
       //de tous ses composants enfants , petits enfants ...
       this.validate();
       
   }
    
    /**
     * Creates new form JPanelPrincipale
     */
    public JPanelPrincipale() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        jbHotel = new javax.swing.JButton();
        jbChambre = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        jToolBar1.setRollover(true);

        jbHotel.setText("Hotel");
        jbHotel.setFocusable(false);
        jbHotel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbHotel.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbHotel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbHotelActionPerformed(evt);
            }
        });
        jToolBar1.add(jbHotel);

        jbChambre.setText("Chambre à coucher");
        jbChambre.setFocusable(false);
        jbChambre.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbChambre.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbChambre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbChambreActionPerformed(evt);
            }
        });
        jToolBar1.add(jbChambre);

        add(jToolBar1, java.awt.BorderLayout.PAGE_START);
    }// </editor-fold>//GEN-END:initComponents

    private void jbChambreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbChambreActionPerformed
        
//        this.add(new JPanelChambre());
//        this.setVisible(true);
    }//GEN-LAST:event_jbChambreActionPerformed

    private void jbHotelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbHotelActionPerformed
        
//        this.add(new JPanelHotel());
//        this.setVisible(true);// que la fenetre
          this.add(new JPanelListeHotels(), BorderLayout.CENTER);
          
    }//GEN-LAST:event_jbHotelActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JButton jbChambre;
    private javax.swing.JButton jbHotel;
    // End of variables declaration//GEN-END:variables
}
