/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package swinga.view;

/**
 *
 * @author Administrateur
 */
public class JPanelListReservation extends javax.swing.JPanel {

    /**
     * Creates new form JPanelListReservation
     */
    public JPanelListReservation() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        jbAjoutPanel = new javax.swing.JButton();
        jbModiflPanel = new javax.swing.JButton();
        jbSupprimerlPanel = new javax.swing.JButton();
        jbGererReservation = new javax.swing.JButton();
        jspCentreHotL = new javax.swing.JScrollPane();
        jtListeHotel = new javax.swing.JTable();

        setLayout(new java.awt.BorderLayout());

        jToolBar1.setRollover(true);

        jbAjoutPanel.setText("Ajouter");
        jbAjoutPanel.setFocusable(false);
        jbAjoutPanel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbAjoutPanel.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbAjoutPanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAjoutPanelActionPerformed(evt);
            }
        });
        jToolBar1.add(jbAjoutPanel);

        jbModiflPanel.setText("Modifier");
        jbModiflPanel.setFocusable(false);
        jbModiflPanel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbModiflPanel.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbModiflPanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbModiflPanelActionPerformed(evt);
            }
        });
        jToolBar1.add(jbModiflPanel);

        jbSupprimerlPanel.setText("Supprimer");
        jbSupprimerlPanel.setFocusable(false);
        jbSupprimerlPanel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbSupprimerlPanel.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jbSupprimerlPanel);

        jbGererReservation.setText("Gérer les réservations");
        jbGererReservation.setFocusable(false);
        jbGererReservation.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbGererReservation.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbGererReservation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbGererReservationActionPerformed(evt);
            }
        });
        jToolBar1.add(jbGererReservation);

        add(jToolBar1, java.awt.BorderLayout.PAGE_START);

        jtListeHotel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jspCentreHotL.setViewportView(jtListeHotel);

        add(jspCentreHotL, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void jbAjoutPanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAjoutPanelActionPerformed
        //this.add(new JPanelHotel(),BorderLayout.CENTER);

        JPanelPrincipale parent =(JPanelPrincipale)this.getParent();
//        parent.remplaceComposanCentral(new JPanelReservation());

    }//GEN-LAST:event_jbAjoutPanelActionPerformed

    private void jbModiflPanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbModiflPanelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbModiflPanelActionPerformed

    private void jbGererReservationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbGererReservationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbGererReservationActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JButton jbAjoutPanel;
    private javax.swing.JButton jbGererReservation;
    private javax.swing.JButton jbModiflPanel;
    private javax.swing.JButton jbSupprimerlPanel;
    private javax.swing.JScrollPane jspCentreHotL;
    private javax.swing.JTable jtListeHotel;
    // End of variables declaration//GEN-END:variables
}
